swagger: '2.0'
info:
  title: goShop Api　
  description: goshop接口文档
  version: 1.0.0
host: 127.0.0.1:8099
schemes:
  - http
  - https
produces:
  - application/json

securityDefinitions:
  APIKeyHeader:
    type: apiKey
    in: header
    name: goshop-token

security:
  - APIKeyHeader: []

paths:
 /address/index:
   get:
     summary: 获取用户收货地址
     description: 根据登录用户获取用户收货地址列表
     tags:
       - 用户收货地址
     parameters:
     responses:
       200:
         description: 成功
         schema:
           $ref: '#/definitions/resp'
 
 /address/detail:
   get:
     summary: 获取用户收货地址详情
     description: 根据收货地址Id，获取用户收货地址详情
     tags:
       - 用户收货地址
     parameters:
       - name: address_id
         in: query
         description: 收货地址id
         required: true
         type: integer
 
     responses:
       200:
         description: 成功
         schema:
           $ref: '#/definitions/resp'
 
 /address/add:
   post:
     summary: 添加收货地址
     description: 根据登录用户， 添加收货地址
     tags:
       - 用户收货地址
     parameters:
       - name: name
         in: formData
         description: 收货人
         required: true
         type: string
 
       - name: mobile
         in: formData
         description: 手机号
         required: true
         type: string
 
       - name: code_prov
         in: formData
         description: 省
         required: true
         type: integer
 
       - name: code_city
         in: formData
         description: 市
         required: true
         type: integer
 
       - name: code_coun
         in: formData
         description: 区
         required: true
         type: integer
 
       - name: address
         in: formData
         description: 详情地址
         required: true
         type: string
 
       - name: room_number
         in: formData
         description: 门牌号，楼房号
         required: true
         type: string
 
       - name: is_default
         in: formData
         description: 是否默认(false|true)
         required: true
         type: string
 
     responses:
       200:
         description: 成功
         schema:
           $ref: '#/definitions/resp'
 
 /address/edit:
   post:
     summary: 编辑收货地址
     description: 根据收货地址Id， 编辑收货地址
     tags:
       - 用户收货地址
     parameters:
       - name: address_id
         in: formData
         description: 用户收货地址Id
         required: true
         type: integer
 
       - name: name
         in: formData
         description: 收货人
         required: true
         type: string
 
       - name: mobile
         in: formData
         description: 手机号
         required: true
         type: string
 
       - name: code_prov
         in: formData
         description: 省
         required: true
         type: integer
 
       - name: code_city
         in: formData
         description: 市
         required: true
         type: integer
 
       - name: code_coun
         in: formData
         description: 区
         required: true
         type: integer
 
       - name: address
         in: formData
         description: 详情地址
         required: true
         type: string
 
       - name: room_number
         in: formData
         description: 门牌号，楼房号
         required: true
         type: string
 
       - name: is_default
         in: formData
         description: 是否默认(false|true)
         required: true
         type: string
 
     responses:
       200:
         description: 成功
         schema:
           $ref: '#/definitions/resp'
 /cart/add:
   post:
     summary: 添加购物车
     description: 添加购物车
     tags:
       - 购物车
     parameters:
       - name: product_id
         in: formData
         description: 商品id
         required: true
         type: integer
 
       - name: product_spec_id
         in: formData
         description: 商品规格id
         required: true
         type: integer
 
       - name: nums
         in: formData
         description: 数量
         required: true
         type: integer
 
       - name: is_plus
         in: formData
         description: 是否是叠加还是覆盖(true|false), 默认是叠加
         required: false
         type: string
 
       - name: is_select
         in: formData
         description: 是否选中(true|false)
         required: true
         type: string
 
     responses:
       200:
         description: 成功
         schema:
           $ref: '#/definitions/resp'
 
 /cart/delete:
   post:
     summary: 删除购物车
     description: 删除购物车
     tags:
       - 购物车
     parameters:
       - name: is_all
         in: formData
         description: 是否全部(1|0), 1全部，选择全部，则无视cart_ids, 清除该登录用户购物车, cart_ids传[]
         required: true
         type: integer
 
       - name: cart_ids
         in: formData
         description: 购物车json, [1, 2, 3]
         required: false
         type: string
 
     responses:
       200:
         description: 成功
         schema:
           $ref: '#/definitions/resp'
 
 /cart/index:
   get:
     summary: 获取购物车
     description: 根据登录用户获取购物车
     tags:
       - 购物车
     parameters:
     responses:
       200:
         description: 成功
         schema:
           $ref: '#/definitions/resp'
 
 /cart/checked:
   post:
     summary: 获取购物车
     description: 根据登录用户获取购物车
     tags:
       - 购物车
     parameters:
       - name: cart_checked
         in: formData
         description: 购物车json, [1, 2, 3]
         required: false
         type: string
 
     responses:
       200:
         description: 成功
         schema:
           $ref: '#/definitions/resp'
 /category/index:
   get:
     summary: 获取分类列表
     description: 获取全部分类列表
     tags:
       - 分类
     parameters:
     responses:
       200:
         description: 成功
         schema:
           $ref: '#/definitions/resp'
 /common/get-area-list:
   get:
     summary: 获取区域省市区
     description: 获取区域省市区列表，已归类
     tags:
       - 省市区
     parameters:
     responses:
       200:
         description: 成功
         schema:
           $ref: '#/definitions/resp'
 /product/index:
   get:
     summary: 获取商品列表
     description: 获取区域省市区列表，已归类
     tags:
       - 商品
     parameters:
       - name: category_id
         in: query
         description: 可根据分类id获取商品列表
         required: false
         type: integer
 
       - name: page
         in: query
         description: 页码
         required: false
         type: integer
 
       - name: page_size
         in: query
         description: 条数,默认20
         required: false
         type: integer
 
     responses:
       200:
         description: 成功
         schema:
           $ref: '#/definitions/resp'
 
 /product/detail:
   get:
     summary: 获取商品详情
     description: 根据商品id，获取商品详情
     tags:
       - 商品
     parameters:
       - name: product_id
         in: query
         description: 商品id
         required: true
         type: integer
 
     responses:
       200:
         description: 成功
         schema:
           $ref: '#/definitions/resp'
 


definitions:
  resp:
    type: object
    properties:
      run_time:
        type: integer
        description: 运行时间
      code:
        type: integer
        description: 提示码
      message:
        type: string
        description: 消息
      data:
        type: object